@AuthServer.Identity.API_HostAddress = https://localhost:7023

# ==========================================
# 1. GÝRÝÞ & TOKEN ÝÞLEMLERÝ
# ==========================================

# @name Login
POST {{AuthServer.Identity.API_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "email": "superadmin@AuthServer.local",
  "password": "Pa$$word123!"
}

###

# Login isteðinden dönen "accessToken" deðerini buraya yapýþtýrýn.
# Diðer tüm istekler bu deðiþkeni kullanacak.
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNDQ4NGNmYi1kYzAyLTQ2N2YtYzc5Ni0wOGRlNmEyZmU1MjciLCJlbWFpbCI6InN1cGVyYWRtaW5AQXV0aFNlcnZlci5sb2NhbCIsImp0aSI6IjZlN2NlNTFiLWE4NDEtNDJkYi04MzM4LTYwMDZiOWM4YWUwMCIsImZ1bGxOYW1lIjoiYWRtaW4gc3VwZXIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiU3VwZXJBZG1pbiIsIkxhYk1hbmFnZXIiXSwiZXhwIjoxNzcwOTA0NDU4LCJpc3MiOiJBdXRoU2VydmVyIiwiYXVkIjoiQXV0aFNlcnZlci5DbGllbnRzIn0.AISIMJMIxvNt38Eph3bR8oNyU5qYEA92NgDZRKmCIX4

### 

# Yönetici Tarafýndan Yeni Kullanýcý Oluþturma
POST {{AuthServer.Identity.API_HostAddress}}/api/UserManagement/create-user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Ahmet",
  "lastName": "Yilmaz",
  "email": "ahmet@lab.local",
  "password": "NewUser123!",
  "roles": ["Basic", "LabTechnician"]
}

###

# Kullanýcý Þifresini Deðiþtirme (Force Reset)
# userId kýsmýna þifresini deðiþtireceðin kullanýcýnýn ID'sini yaz.
POST {{AuthServer.Identity.API_HostAddress}}/api/UserManagement/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "d22faff4-b313-4b8c-6966-08de6a3c29ee",
  "newPassword": "ResetPa$$123"
}
###
# Kullanýcý Bilgilerini Güncelle (Ad, Soyad, Email)
# userId: Güncellenecek kiþinin ID'si
PUT {{AuthServer.Identity.API_HostAddress}}/api/UserManagement/update-user
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "userId": "d22faff4-b313-4b8c-6966-08de6a3c29ee",
  "firstName": "Mehmet",
  "lastName": "Demir",
  "email": "mehmet.yeni@lab.local"
}